package com.yash.android.pokemoncards.viewmodels

import androidx.lifecycle.ViewModel
import com.yash.android.pokemoncards.models.Pokemon

class PokemonListViewModel: ViewModel() {
    val pokemons = listOf<Pokemon>(
        Pokemon(
            "Bulbasaur",
            "bulbasaur.png",
            0.7,
            6.9,
            45,
            49,
            49,
            65,
            65,
            45
        ),
        Pokemon(
            "Arbok",
            "arbok.png",
            3.5,
            65.0,
            60,
            95,
            69,
            65,
            79,
            80
        ),
        Pokemon(
            "Charmander",
            "charmander.png",
            0.6,
            8.5,
            39,
            52,
            43,
            60,
            50,
            65
        ),
        Pokemon(
            "Mewtwo",
            "mewtwo.png",
            2.0,
            122.0,
            106,
            110,
            90,
            154,
            90,
            130
        ),
        Pokemon(
            "Moltres",
            "moltres.png",
            2.0,
            60.0,
            90,
            100,
            90,
            125,
            85,
            90
        ),
        Pokemon(
            "Onix",
            "onix.png",
            8.8,
            210.0,
            35,
            45,
            160,
            30,
            45,
            70
        ),
        Pokemon(
            "Pikachu",
            "pikachu.png",
            0.4,
            6.0,
            35,
            55,
            40,
            50,
            50,
            90
        ),
        Pokemon(
            "Treecko",
            "treecko.png",
            0.5,
            5.0,
            40,
            45,
            35,
            65,
            55,
            70
        )
    )
}